### PR TITLE
Fixing #94 and #106

### PR DESCRIPTION
**Pull request by oganm**

### CODE REVIEW

**Comment by arteymix** [comment]
That's a bit of an odd watcher. Can you check if the clear all selection button at the bottom of the settings still work?

**Comment by oganm** [comment]
Nope very much broken..

Another new if not functionally too important issue is that if i

- select a mouse and a human microarray
- select human

the mouse microarray will still be selected despite not being part of the tree anymore

**Comment by oganm** [comment]
This latest commit fixes the clear all issue using a ref. I am unsure if keeping non-existent parts of the tree selected is a real issue since people may want to preserve their selections regardless

**Comment by oganm** [comment]
@arteymix this removes the components/PlatformSelector.js. it seemed to be an earlier version of TechnologyTypeSelector. and creates a platformConstants.js to import some constants

**Pull request merged**
